Done second task
js-tasks-ru/js-20220209_oleg-novikov26-yandex-ru pull request #2
Opened 2022-02-14 00:06 UTC by Olnovikov

2022-02-14 00:07 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-15 22:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        case 'desc': return sortedArr.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-02-15 22:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const keyValueArr = Object.entries(obj)
good 👍

2022-02-15 22:17 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const keyValueArr = Object.entries(obj)
good 👍

2022-02-15 22:17 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-16 11:15 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-16 14:10 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
good 👍

2022-02-16 14:10 UTC, dosandk approved these changes
good 👍

2022-02-16 14:11 UTC, merged